# Generated by Django 4.2.7 on 2023-11-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0005_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'authors')},
        ),
    ]
